# Generated by Django 3.1.7 on 2021-03-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_artist_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='track',
            field=models.ManyToManyField(to='music.Track'),
        ),
    ]
