# Generated by Django 3.1.7 on 2021-03-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210319_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
